### ISSUE TITLE
Network devices specified in Metal3DataTemplate spec.networkData can be identified by an annotation of a machine object

### ISSUE THREAD

**Issue by fhaftmann** [metal3-io/cluster-api-provider-metal3#1208]
**User Story**

As an operator I would like to use *spec.networkData* in *Metal3DataTemplate* to configure a machine’s network with network interfaces identified by a MAC address provided by an annotation of a machine object, similar as already possible using *spec.metaData.fromAnnotations*, to provide distinct MAC addresses for machines sharing the same *Metal3DataTemplate*.

**Detailed Description**

It is already possible to specify

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: my-datatemplate
spec:
  clusterName: my-cluster
  metaData:
    fromAnnotations:
    - key: device_macaddress
      object: baremetalhost
      annotation: device_macaddress
```

to construct meta data from annotations (in this example, from *baremetalhost*s).

This should also carry over to sth. like

```yaml
kind: Metal3DataTemplate
metadata:
  name: my-datatemplate
spec:
  clusterName: my-cluster
  networkData:
    links:
      ethernets:
        - type: phy
           id: device
           macAddress:
             fromAnnotations:
               - key: device_macaddress
                 object: baremetalhost
                 annotation: device_macaddress
```

**Anything else you would like to add:**

It seems feasible to use the existing implementation for *metaData* for *networkData* also.

Currently, *macAddress* can either be
a) a static string
b) derived from a network interface name (after inspection)

Both seem too inflexible in general:
a) seems only be reasonable if *my-datatemplate* refers to exactly one machine (which is a degenerate special case)
b) seems only be feasible if *my-datatemplate* refers to a bunch of machines which are similar enough to share the same schema for network device names.

/kind feature
