### ISSUE TITLE
IP reuse: Deleting M3D cascades to IPClaims across namespaces

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/cluster-api-provider-metal3#1250]
**What steps did you take and what happened:**

1. Initialize CAPM3 with [IP reuse enabled](https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/docs/ip_reuse.md#how-to-enable-ip-reuse). This is very important to trigger the bug!
2. Create two identical clusters in separate namespaces.
   - They should have an IPPool each and allocate IPAddresses from them (no need to use preAllocations though).
   - Make sure that the M3DTs are named the same in each namespace.
3. Check that you have (at least) one M3D and IPClaim in each namespace
4. Delete one cluster. Alternatively: Delete just one M3D.
5. Check the IPClaims again. They are gone in both namespaces!

**What did you expect to happen:**

1. The IPClaim(s) in the other namespace should not be affected when the M3D is deleted from the first namespace!
2. (The M3D should not be deleted while there is a M3DC still using it. We can create a separate issue for this.)

**Anything else you would like to add:**

We suspect that the issue is in the ownerRef of the IPClaims or the code around that. They do not include the namespace!

```yaml
  ownerReferences:
  - apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    controller: true
    kind: Metal3Data
    name: my-cluster-controlplane-template-0
    uid: ec4a98f2-f388-43b9-a643-c320ec21942f
```
The UID should still be different, but perhaps we are not checking this properly. I remember some comment about not checking UIDs since they can change when doing `clusterctl move`.

**Environment:**

- Cluster-api version: v1.4.7 and v1.5.2 tested
- Cluster-api-provider-metal3 version: v1.4.5 and v1.5.1 tested
- Environment (metal3-dev-env or other): other
- Kubernetes version: (use `kubectl version`): v1.27.3

/kind bug
