### ISSUE TITLE
Metal3DataTemplate with templateReference cannot be deleted while Metal3Data with matching name exists

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/cluster-api-provider-metal3#1357]
**What steps did you take and what happened:**

1. Create a Cluster with Metal3 for infra and make sure it has a MachineDeployment that uses a Metal3DataTemplate with a `templateReference`.
2. Create another Metal3DataTemplate and Metal3MachineTemplate that references it.
3. Update the MachineDeployment to use the new Metal3MachineTemplate and Metal3DataTemplate so that a rollout is triggered.
4. When the rollout is complete, delete the old Metal3DataTemplate that is no longer used.
5. **The Metal3DataTemplate cannot be deleted because it thinks it is still in use**

**What did you expect to happen:**

Old Metal3DataTemplates should be possible to delete when they are no longer used.

**Anything else you would like to add:**

The issue happens only when using `templateReference`. It is unclear to me what the function of this field is.
I have been able to do rollouts without issues when not using the `templateReference` and can then delete the old Metal3DataTemplate.

**Environment:**

- Cluster-api version: v1.5.3
- Cluster-api-provider-metal3 version: v1.5.2
- Environment (metal3-dev-env or other): other
- Kubernetes version: (use `kubectl version`): v1.28.3

/kind bug

**Comment by peppi-lotta** [comment]
# templateReference investigation

## Questions to answer

- Is templateReference actually needed for anything?
- Does having templateReference prevent deletion of resources in any situation where it shouldn’t?
- Do we fix the bug or remove templateReference all together?

## Beginning

| Resource           |  Name                    | templateReference to  |
|--------------------|--------------------------|-----------------------|
| Metal3DataTemplate | test1-workers-template   | -                     |
| Metal3Data         | test1-workers-template-0 | 🠋                     |

```
kubectl get metal3data -n metal3 test1-workers-template-0 -o yaml
...
spec:
  claim:
    name: test1-qtmqg-5br6d
    namespace: metal3
  metaData:
    name: test1-qtmqg-5br6d-metadata
    namespace: metal3
  networkData:
    name: test1-qtmqg-5br6d-networdata
    namespace: metal3
  template:
    name: test1-workers-template
    namespace: metal3
```

New secrets were created. Metal3DataTemplate test1-workers-template can not be deleted because it is in use.

## Do rolling update where new Metal3DataTemplate's templateReference is set to current Metal3DataTemplate.

| Resource           |  Name                    | templateReference to   |
|--------------------|--------------------------|------------------------|
| Metal3DataTemplate | test1-workers2-template  | test1-workers-template |
| Metal3Data         | test1-workers-template-0 | 🠋                      |
```
kubectl get metal3data -n metal3 test1-workers-template-0 -o yaml
...
spec:
  claim:
    name: test1-8vlzf-nwqf5
    namespace: metal3
  metaData:
    name: test1-8vlzf-nwqf5-metadata
    namespace: metal3
  networkData:
    name: test1-8vlzf-nwqf5-networdata
    namespace: metal3
  template:
    name: test1-workers2-template
    namespace: metal3
  templateReference: test1-workers-template
```
New secrets were created. Metal3DataTemplate test1-workers-template can be deleted.

## Do another rolling update where new Metal3DataTemplate's templateReference is set to current Metal3DataTemplate.

| Resource           |  Name                    | templateReference to   |
|--------------------|--------------------------|------------------------|
| Metal3DataTemplate | test1-workers3-template  | test1-workers2-template|
| Metal3Data         | test1-workers2-template-0| 🠋                      |

```
kubectl get metal3data -n metal3 test1-workers2-template-0 -o yaml
...
spec:
  claim:
    name: test1-6xwqh-lxh69
    namespace: metal3
  metaData:
    name: test1-6xwqh-lxh69-metadata
    namespace: metal3
  networkData:
    name: test1-6xwqh-lxh69-networdata
    namespace: metal3
  template:
    name: test1-workers3-template
    namespace: metal3
  templateReference: test1-workers2-template
```

New secrets were created. Metal3DataTemplate test1-workers-template can be deleted.

## Referencing an older template (iterations 3, 4, 5)

| Resource           |  Name                    | templateReference to   |
|--------------------|--------------------------|------------------------|
| Metal3DataTemplate | test1-workers5-template  | test1-workers3-template|
| Metal3Data         | test1-workers3-template-0| 🠋                      |

```
kubectl get metal3data -n metal3 test1-workers3-template-0 -o yaml
...
  template:
    name: test1-workers5-template
    namespace: metal3
  templateReference: test1-workers3-template
```

New secrets were created. Metal3DataTemplate test1-workers3-template can be deleted. Metal3DataTemplate test1-workers4-template can not be deleted.

## Referencing template that is no longet on the machine.
| Resource           |  Name                    | templateReference to   |
|--------------------|--------------------------|------------------------|
| Metal3DataTemplate | test1-workers6-template  | test1-workers3-template|
| Metal3Data         | test1-workers3-template-1| 🠋                      |

```
kubectl get metal3data -n metal3 test1-workers3-template-1 -o yaml
...
  template:
    name: test1-workers6-template
    namespace: metal3
  templateReference: test1-workers3-template
```

New secrets were created. Metal3DataTemplate test1-workers4-template can not be deleted. Metal3DataTemplate test1-workers5-template can not be deleted.

## Rolling with template with no templateReference.
| Resource           |  Name                    | templateReference to   |
|--------------------|--------------------------|------------------------|
| Metal3DataTemplate | test1-workers7-template  | -                      |
| Metal3Data         | test1-workers7-template-0| -                      |

```
kubectl get metal3data -n metal3 test1-workers7-template-0 -o yaml
...
  template:
    name: test1-workers7-template
    namespace: metal3
```

New secrets were created. Metal3DataTemplate test1-workers4-template can be deleted. Metal3DataTemplate test1-workers5-template can be deleted.

## Summary 
The templateReference mostly seems to affect the name of metal3Data. Is there any actual use for this feature. I don't know yet...
