### ISSUE TITLE
vlanID field misdocumented as vlanId

### ISSUE THREAD

**Issue by macaptain** [metal3-io/cluster-api-provider-metal3#185]
**What steps did you take and what happened:**
I applied a Metal3DataTemplate manifest with the following `spec[networkData[links[vlans]]]` field:

```
      vlans:
        - id: "eth1.3"
          mtu: 1500
          macAddress:
            fromHostInterface: eth1
          vlanId: 3
          vlanLink: "eth1"
```

vlanId (lowercase d) is what's documented in the API: https://github.com/metal3-io/cluster-api-provider-metal3/blob/master/docs/api.md#links-specifications **links/vlans/vlanId**. But in the code the struct expects the field 'vlanID': https://github.com/metal3-io/cluster-api-provider-metal3/blob/329ae2f714b54555c71a484ed6d50e620f097273/api/v1alpha4/metal3datatemplate_types.go#L225

**What did you expect to happen:**

I expected my Metal3DataTemplate to have `vlanId: 3` set, instead `vlanID: 0` was set.

**Environment:**

- Cluster-api version: v1alpha4
- CAPBM version: be9faea
- Minikube version: N/A
- environment (metal3-dev-env or other): metal3-dev-env
- Kubernetes version: (use `kubectl version`): N/A

/kind bug
