### ISSUE TITLE
Wrong replicas count in kubeadmcontrolplane status

### ISSUE THREAD

**Issue by Xenwar** [metal3-io/cluster-api-provider-metal3#21]
**What steps did you take and what happened:**
- Run metal3-dev-env with 4 nodes
- provision a control plane node
- Scale up by changing the replicas to 5 or 7.

The result, status.replicas is 5.

**What did you expect to happen:**
status.replicas should be 4
 
**Anything else you would like to add:**
1. If you make spec.replicas 5 or 7 does not make a difference. 
    status.replicas will be 5.
2. The logs of the controllers seem to show correct behavior. 
3. This is not a CAPI problem, but that of a provider.
4. Relevant logs are added comments below

**Environment:**

- Cluster-api version: v1alpha3
- CAPBM version: v1alpha3
- Minikube version: v1.8.2
- environment: metal3-dev-env:
- Kubernetes version: 1.17.0

/kind bug

**Comment by Xenwar** [comment]
kubeadmControlPlane logs
```

E0317 13:08:58.089626       1 kubeadm_control_plane_controller.go:470] controllers/KubeadmControlPlane "msg"="waiting for control plane to pass control plane health check before adding an additional control plane machine" "error"="control plane machine metal3/test1-controlplane-zpnh9 has no status.nodeRef" "cluster"="test1" "kubeadmControlPlane"="test1-controlplane" "namespace"="metal3" 
I0317 13:09:04.787252       1 kubeadm_control_plane_controller.go:270] controllers/KubeadmControlPlane "msg"="Scaling up control plane" "cluster"="test1" "kubeadmControlPlane"="test1-controlplane" "namespace"="metal3" "Desired"=5 "Existing"=4

```

**Comment by Xenwar** [comment]
capi controller manager logs
```

E0317 13:19:37.358944       1 machine_controller.go:232] controllers/Machine "msg"="Reconciliation for Machine asked to requeue" "error"="Infrastructure provider for Machine \"test1-controlplane-ttzbx\" in namespace \"metal3\" is not ready, requeuing: requeue in 30s" "cluster"="test1" "machine"="test1-controlplane-ttzbx" "namespace"="metal3" 
I0317 13:20:07.366486       1 machine_controller_noderef.go:53] controllers/Machine "msg"="Machine doesn't have a valid ProviderID yet" "cluster"="test1" "machine"="test1-controlplane-ttzbx" "namespace"="metal3" 
E0317 13:20:07.366747       1 machine_controller.go:232] controllers/Machine "msg"="Reconciliation for Machine asked to requeue" "error"="Infrastructure provider for Machine \"test1-controlplane-ttzbx\" in namespace \"metal3\" is not ready, requeuing: requeue in 30s" "cluster"="test1" "machine"="test1-controlplane-ttzbx" "namespace"="metal3" 

```

**Comment by Xenwar** [comment]
```
kubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  finalizers:
  - kubeadm.controlplane.cluster.x-k8s.io
  labels:
    cluster.x-k8s.io/cluster-name: test1
  name: test1-controlplane
  namespace: metal3
  ownerReferences:
  - apiVersion: cluster.x-k8s.io/v1alpha3
    blockOwnerDeletion: true
    controller: true
    kind: Cluster
    name: test1
    uid: 3e9f10fe-54de-4318-aa56-cfd61ffe5c39
  uid: a09a6baa-710c-42f8-aab1-008df30d8bba
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: Metal3MachineTemplate
    name: test1-controlplane
    namespace: metal3
  kubeadmConfigSpec:
    clusterConfiguration:
      .
    files:
    - content: ...
    initConfiguration:
      .
    joinConfiguration:
      .
    postKubeadmCommands:
    - ...
    preKubeadmCommands:
    - ...
  replicas: 7
  version: v1.17.0
status:
  initialized: true
  replicas: 5
  selector: cluster.x-k8s.io/cluster-name=test1,cluster.x-k8s.io/control-plane=
  unavailableReplicas: 5
  updatedReplicas: 5
```

**Comment by maelk** [comment]
Why is this not a CAPI problem ?

**Comment by Xenwar** [comment]
As was indicated in #3 of the issue description, CAPI is not aware of the infra. It relies on the information we convey to it. So, our controller should be responsible for that.

**Comment by maelk** [comment]
I still don't get the problem. If you set the replicas count to be 5, is it not expected that the status would be 5 replicas ?

**Comment by Xenwar** [comment]
Please see the next comment(s) for the same process using deployments/pods. 
Notice that the increment is done gradually and at each stage the numbers are shown. 

At the beginning we a deployment with replica of 1. Then, we increase the replicas to 20.

**Comment by Xenwar** [comment]
```
➜  ~ kubectl get deployments -w
NAME       READY   UP-TO-DATE   AVAILABLE   AGE
myserver   1/20    20           1           3m59s
myserver   2/20    20           2           4m
myserver   3/20    20           3           4m
myserver   4/20    20           4           4m2s
myserver   5/20    20           5           4m4s
myserver   6/20    20           6           4m6s

```

**Comment by Xenwar** [comment]
```
➜  ~ kubectl get deployments myserver -o yaml
apiVersion: apps/v1
kind: Deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 20
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: myserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:

status:
  availableReplicas: 15
  conditions:
  - lastTransitionTime: "2020-03-23T05:09:22Z"
    lastUpdateTime: "2020-03-23T05:12:26Z"
    message: ReplicaSet "myserver-6c8c7c8d9f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-03-23T05:13:47Z"
    lastUpdateTime: "2020-03-23T05:13:47Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 15
  replicas: 20
  unavailableReplicas: 5
  updatedReplicas: 20
```
