### ISSUE TITLE
CAPBM removes  networkData from  BareMetalHost

### ISSUE THREAD

**Issue by jingvar** [metal3-io/cluster-api-provider-metal3#23]
**What steps did you take and what happened:**

1. Create a BareMetalHost with  spec\networkData and Secret for it. 
2. Look at description the BareMetalHost and find "networkData".
3. Wait for status "Ready" of BMH.
4. Create Cluster, BareMetalCluster, Machine, BareMetalMachine.
5. Look at description the BareMetalHost and try to find networkData.

**What did you expect to happen:**
When CAPBM update BMH it removes  networkData.

**Anything else you would like to add:**
**Environment:**

- Cluster-api version: v2
- CAPBM version: v2
- Minikube version: n/a
- environment : other
- Kubernetes version: (use `kubectl version`): 1.16.3

/kind bug

**Comment by jingvar** [comment]
---
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: test1
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/24
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.96.0.0/12
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: BareMetalCluster
    name: test1
    namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: BareMetalCluster
metadata:
  name: test1
  namespace: default
spec:
  apiEndpoint: http://192.168.100.120:6443
  noCloudProvider: false

**Comment by jingvar** [comment]
```
apiVersion: v1
data:
  password: YWRtaW4=
  username: YWRtaW4=
kind: Secret
metadata:
  name: test1-baremetalhost-secret
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: test1-baremetalhost
  labels:
    baremetal: test1-baremetalhost
spec:
  bmc:
    address: ipmi://192.168.100.1:623
    credentialsName: test1-baremetalhost-secret
  online: true
  bootMACAddress: 52:54:00:ef:4b:40
  networkData:
    name: test1-baremetalhost-network
    namespace: default
```

**Comment by jingvar** [comment]
```
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Machine
metadata:
  name: test1-controlplane-0
  labels:
    cluster.x-k8s.io/control-plane: "true"
    cluster.x-k8s.io/cluster-name: "test1"
spec:
  version: 1.16.1
  bootstrap:
    data: I2Nsb3VkLWNvbmZpZwpydW5jbWQ6CiAgLSBlY2hvICdDb25maWd1cmUgTG9jYWwgQ2xvdWQgSW5pdCBTdGFnZScKICAtIGVjaG8gJ3VidW50dTpyMDB0bWUnIHwgY2hwYXNzd2QK
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: BareMetalMachine
    name: test1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: BareMetalMachine
metadata:
  name: test1
spec:
  image:
    url: http://192.168.10.1/images/xenial-server-cloudimg-amd64-disk1.img
    checksum: http://192.168.10.1/images/xenial-server-cloudimg-amd64-disk1.img.md5sum
  hostSelector:
    matchLabels:
      baremetal: test1-baremetalhost
```

**Comment by jingvar** [comment]
kustomization.yaml
```
---
secretGenerator:
  - name: test1-baremetalhost-network
    files:
    - networkData
```
networkData
```
---
links:
- name: pxe0
  id: pxe0
  type: phy
  ethernet_mac_address: 52:54:00:ef:4b:40
.......
```

**Comment by dhellmann** [comment]
I would expect the cluster-api provider to need to set all of the metadata for the host as part of configuring it to become a node. The system should be designed so that users don't need to set information in individual hosts before provisioning them, since most of the settings should come from the Machine/MachineSet.

**Comment by jingvar** [comment]
I can't find "network" is in the Machine/MachineSet ...

**Comment by dhellmann** [comment]
> I can't find "network" is in the Machine/MachineSet ...

It may not be there, yet. My point is that the main API for configuring provisioning a node is the Machine or MachineSet, not the host itself. If we're missing input fields or just not setting things on the host, those are bugs.

**Comment by maelk** [comment]
This is a known bug with v1alpha2. It was fixed in v1alpha3. Regarding the addition of the networkData field from CAPM3, this is something that we are missing indeed. You can create a feature request to track the work. FYI, we are right now working on adding the metadata field, so my guess would be that networkData could be next.

**Comment by maelk** [comment]
Can you please try with v1alpha3 and let us know if you still hit the problem ?

**Comment by jingvar** [comment]
> Can you please try with v1alpha3 and let us know if you still hit the problem ?
I tried with v1alpha3 and have got different issue.
1. I had very long time with BMH in "registering" state.
2. after provisioning, network Data was in BMH, but was not into config drive

**Comment by jingvar** [comment]
```
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: test1
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.96.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/24"]
    serviceDomain: "cluster.local"
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: Metal3Cluster
    name: test1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: Metal3Cluster
metadata:
  name: test1
spec:
  controlPlaneEndpoint:
    host: 192.168.100.120
    port: 6443
  noCloudProvider: true
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  name: test1
  labels:
    cluster.x-k8s.io/control-plane: "true"
    cluster.x-k8s.io/cluster-name: "test1"
spec:
  clusterName: test1
  version: 1.16.1
  bootstrap:
    configRef:
      name: test1
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
      kind: KubeadmConfig
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: Metal3Machine
    name: test1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: Metal3Machine
metadata:
  name: test1
spec:
  image:
    url: http://192.168.10.1/images/xenial-server-cloudimg-amd64-disk1.img
    checksum: http://192.168.10.1/images/xenial-server-cloudimg-amd64-disk1.img.md5sum
  hostSelector:
    matchLabels:
      baremetal: test1-baremetalhost

---
kind: KubeadmConfig
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
metadata:
  name: test1
spec:
  initConfiguration:
    nodeRegistration:
      name: '{{ ds.meta_data.name }}'
      kubeletExtraArgs:
        node-labels: 'metal3.io/uuid={{ ds.meta_data.uuid }}'
  preKubeadmCommands:
    - echo 'ubuntu:r00tme' | chpasswd

```

**Comment by maelk** [comment]
Did you define the networkData in the BMH ? Can you also show your BMH and networkData ?

**Comment by jingvar** [comment]
> Did you define the networkData in the BMH ? Can you also show your BMH and networkData ?

```
apiVersion: v1
data:
  password: YWRtaW4=
  username: YWRtaW4=
kind: Secret
metadata:
  name: test1-baremetalhost-secret
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: test1-baremetalhost
  labels:
    baremetal: test1-baremetalhost
spec:
  bmc:
    address: ipmi://192.168.100.1:623
    credentialsName: test1-baremetalhost-secret
  online: true
  bootMACAddress: 52:54:00:ef:4b:40
  networkData:
    name: test1-baremetalhost-network
    namespace: default
```

**Comment by jingvar** [comment]
networkData
```
---
links:
- name: pxe0
  id: pxe0
  type: phy
  ethernet_mac_address: 52:54:00:ef:4b:40
- name: oam0
  type: phy
  id: oam0
  ethernet_mac_address: 52:54:00:ef:fb:eb
- name: stor0
  id: stor0
  type: phy
  ethernet_mac_address: 52:54:00:a9:1c:65
- name: underlay0
  type: phy
  id: underlay0
  ethernet_mac_address: 52:54:00:d7:06:d2
networks:
- id: pxe0-ipv4
  type: ipv4
  link: pxe0
  ip_address: 192.168.10.120
  netmask: 255.255.255.0
- id: oam0-ipv4
  type: ipv4
  link: oam0
  ip_address: 192.168.100.120
  netmask: 255.255.255.0
  routes:
  - network: 0.0.0.0
    netmask: 0.0.0.0
    gateway: 192.168.100.1
- id: stor0-ipv4
  type: ipv4
  link: stor0
  ip_address: 192.168.20.120
  netmask: 255.255.255.0
- id: underlay0-ipv4
  type: ipv4
  link: underlay0
  ip_address: 192.168.30.120
  netmask: 255.255.255.0
services:
- address: 8.8.8.8
  type: dns

```
