### ISSUE TITLE
Use Metal3Machines with other CAPI Clusters

### ISSUE THREAD

**Issue by AMacedoP** [metal3-io/cluster-api-provider-metal3#2526]
**User Story**

As a user I would like to use the Metal3 CAPI provider to instantiate baremetal machines to use with other CAPI clusters such a Openstack Cluster

**Detailed Description**

The usecase I have in mind is to have a Kubernetes clusters with virtualized control plane nodes (using Openstack in this particular case) and baremetal worker nodes.

I tried creating a cluster with:

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: microos-m3
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: RKE2ControlPlane
    name: microos-m3-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: OpenStackCluster
    name: microos-m3
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: microos-m3-md-0
  namespace: default
spec:
  clusterName: microos-m3
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: RKE2ConfigTemplate
          name: microos-m3-md-0
      clusterName: microos
      failureDomain: null
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        name: microos-m3-md-0
      version: v1.30.2+rke2r1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1 # Adjust version for CAPM3
kind: Metal3MachineTemplate
metadata:
  name: microos-m3-md-0
  namespace: default
spec:
  template:
    spec:
      image:
        url: http://10.100.3.51:8080/openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2
        checksum: http://10.100.3.51:8080/openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2.sha256
        checksumType: sha256
      networkData:
        name: dl-50-network-data
      userData:
        name: dl-50-user-data
      hostSelector:
        matchLabels:
          capm3: "true"
      providerID: metal3://dl-50
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: RKE2ConfigTemplate
metadata:
  name: microos-m3-md-0
  namespace: default
spec:
  template:
    spec:
      agentConfig:
        airGapped: false
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: microos-m3
  namespace: default
spec:
  externalNetwork:
    id: f7bd4a54-8208-4bf7-93ea-fcb1478d27b5
  identityRef:
    cloudName: openstack
    name: microos-m3-cloud-config
  disablePortSecurity: true
  managedSubnets:
  - cidr: "10.0.0.0/24"
    dnsNameservers:
    - 10.100.16.1
  bastion:
    enabled: true
    spec:
      flavor: m1.large
      image:
        id: d58d4ab1-6737-4864-a7dc-c59708da0b52
      sshKeyName: ssh-key
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: microos-m3-control-plane
  namespace: default
spec:
  template:
    spec:
      flavor: m1.large
      image:
        id: d58d4ab1-6737-4864-a7dc-c59708da0b52
      sshKeyName: ssh-key
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: RKE2ControlPlane
metadata:
  name: microos-m3-control-plane
  namespace: default
spec:
  version: v1.30.2+rke2r1
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: OpenStackMachineTemplate
      name: microos-m3-control-plane
    nodeDrainTimeout: 2m
  replicas: 1
  serverConfig:
    cloudProviderName: external
    cni: cilium
    etcd:
      backupConfig:
        retention: "10"
        scheduleCron: "*/15 * * * *"
  rolloutStrategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
```

With the BMH manifest:

```yaml
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: dl-50
  labels:
    capm3: "true"
spec:
  online: true
  bootMACAddress: b4:7a:f1:2d:0a:78
  bootMode: UEFI
  bmc:
    address: ilo5-virtualmedia://10.100.2.52:443/redfish/v1/Systems/1
    credentialsName: dl-50
    disableCertificateVerification: true
  rootDeviceHints:
    wwn: "nvme.c0a9-323131384535394442423134-435431303030503253534438-00000001"
```

And saw this logs in the capm3-controller

```
I0428 17:26:36.582847       1 metal3machine_controller.go:141] "Waiting for Metal3Cluster Controller to create the Metal3Cluster" logger="controllers.Metal3Machine.Metal3Machine-controller" metal3-machine="default/microos-m3-md-0-b6vfv-n824v" machine="microos-m3-md-0-b6vfv-n824v" cluster="microos-m3"
```

Is this feature planned?

/kind feature
