### ISSUE TITLE
Wrong contract labels for v1alpha4

### ISSUE THREAD

**Issue by maelk** [metal3-io/cluster-api-provider-metal3#45]
**What steps did you take and what happened:**
The cluster labels applied in config/crd/kustomization.yaml are 

```
commonLabels:
  cluster.x-k8s.io/v1alpha2: v1alpha2
  cluster.x-k8s.io/v1alpha3: v1alpha3
  cluster.x-k8s.io/v1alpha4: v1alpha3
```

**What did you expect to happen:**
They should be 
```
commonLabels:
  cluster.x-k8s.io/v1alpha2: v1alpha2
  cluster.x-k8s.io/v1alpha3: v1alpha3,v1alpha4
```
with the correct separator when this PR is merged : https://github.com/kubernetes-sigs/cluster-api/issues/2775

**Environment:**

- Cluster-api version: v0.3.2
- CAPBM version: master

/kind bug
